version: '2'
volumes:
  webroot:
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/pattern.conf:/etc/nginx/conf.d/default.conf
      - webroot:/webroot/
    depends_on:
      - web
  web:
    build: .
    environment:
      - PN_AUTH_TOKEN=
      - PN_DB_URI=
      - PN_DUNYA_HOST=dunya.compmusic.upf.edu
    volumes:
          - webroot:/webroot/
    command: python api.py
